version: "3.4"

networks:
  main:
  qa:
  client:

services:
  api:
    image: api:latest
    ports:
      - "5000:5000"
    environment:
      - SERVICE_DISCOVERY_URL=http://host.docker.internal:7000
      - Logging:LogLevel:Default=Warning
    networks:
      - main
      - qa
      - client
  api-dependency:
    image: api-dependency:latest
    ports:
      - "6000:5000"
    environment:
      - Logging:LogLevel:Default=Warning
    networks:
      - main
      - qa
  api-service-discovery:
    image: api-service-discovery:latest
    ports:
      - "7000:5000"
    environment:
      - DEPENDENCY_SERVICE=http://host.docker.internal:6000
      - Logging:LogLevel:Default=Warning
    networks:
      - main

  tests-int:
    image: tests-int:latest
    networks:
      - qa
  tests-e2e:
    image: tests-e2e:latest
    networks:
      - client
  tests-perf:
    image: loadimpact/k6:latest
    networks:
      - client
    ports:
      - "6565:6565"
    volumes:
      - ./tests/perf:/scripts
